### ISSUE TITLE
How to show the bubble always without animating

### ISSUE THREAD

**Issue by shahidcodes** [alantoa/react-native-awesome-slider#56]
Is there any way to show the bubble always? and show it in the buttom instead of top?

**Comment by AlirezaHadjar** [comment]
Hi @shahidcodes 

There isn't a way always to display the bubble. But you can patch the code, as it requires changing only a few lines of code to disable the animation and set the default opacity to `1` instead of `0` 

As for the bubble Y translation, you can set its `translateY` using `bubbleTranslateY` but you also need to patch the package and rotate the `triangle` to point upward.

**Comment by shahidcodes** [comment]
I did exactly that
