### ISSUE TITLE
NPM peerdependency error

### ISSUE THREAD

**Issue by Hannes1** [alantoa/react-native-awesome-slider#6]
Hi, I'm getting the following error when I try to npm install

```
npm ERR! Found: react-native-reanimated@2.4.1
npm ERR! node_modules/react-native-reanimated
npm ERR!   react-native-reanimated@"^2.4.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react-native-reanimated@">2" from react-native-awesome-slider@1.3.0
npm ERR! node_modules/react-native-awesome-slider
npm ERR!   react-native-awesome-slider@"*" from the root project
```

Looks like the peerd dependency in package.json isn't compatible with the latest reainimated@2.4.1?

I saw other packages do the following, maybe it can help:
```json
  "peerDependencies": {
    "react-native-reanimated": ">=2.0.0"
  },
```

PS thanks for the slider can't wait to try it!

**Comment by alantoa** [comment]
@Hannes1  Hi!
I think both will work, and  I use it well.
I guess it's a node version problem, I use node16~17.

But your compatibility is better, I fixed it.
Now because of computer problems, I need to release the version tomorrow.
You can try to install:
```sh
yarn add git+https://github.com/alantoa/react-native-awesome-slider
```

If you have any question, contact me anytime!

**Comment by Hannes1** [comment]
@alantoa thanks for the quick response it's working!

**Comment by alantoa** [comment]
You're welcome!
